### ISSUE TITLE
COMMENTS QA CHECKLIST

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme-2023#94]
* Editing
  - [ ] Click Add/Edit Comment --> 
     - [ ] "Edit" and "Add Comment" is disabled EVERYWHERE
     - [ ] But not disabled for others on network
  - [ ] Click Save -->
    - [ ] Comment Status Bar shows update
    - [ ] Comment Status Bar on Network computer shows update
* Deleting
  - [ ] Delete root --> comment is removed
  - [ ] Delete reply to root --> comment is removed
  - [ ] Delete root with replies --> 
     - [ ] root is removed if admin
     - [ ] root is marked deleted if not admin
  - [ ] Delete reply to reply root -->
     - [ ] reply root is removed if admin
     - [ ] reply root is marked deleted if not admin
  - [ ] Delete reply to reply --> comment is removed
  - [ ] REPEAT for Network
* Canceling
  - [ ] Add new comment, click Cancel --> "Click to add comment" is visible
  - [ ] Reply to comment, click Cancel --> "Click to add comment" is visible
  - [ ] Edit comment, click Cancel --> "Click to add comment" is visible, any text is restored
  - [ ] Edit comment, change type, click Cancel --> "Click to add comment" is visible, Comment Type and any text is restored
* Closing
  - [ ] Click "X",  -->  comments are marked read
  - [ ] Click "Close",  -->  comments are marked read
